--- !ruby/object:Minesweeper::Board
num_of_bombs: 10
board:
- - &70116767962900 !ruby/object:Minesweeper::Tile
    flagged: false
    revealed: true
    row: 0
    col: 0
    neighbors:
    - &70116767950480 !ruby/object:Minesweeper::Tile
      flagged: false
      revealed: true
      row: 0
      col: 1
      neighbors:
      - *70116767962900
      - &70116767947400 !ruby/object:Minesweeper::Tile
        flagged: false
        revealed: true
        row: 0
        col: 2
        neighbors:
        - *70116767950480
        - &70116767945400 !ruby/object:Minesweeper::Tile
          flagged: false
          revealed: true
          row: 0
          col: 3
          neighbors:
          - *70116767947400
          - &70116767944040 !ruby/object:Minesweeper::Tile
            flagged: false
            revealed: true
            row: 0
            col: 4
            neighbors:
            - *70116767945400
            - &70116767941640 !ruby/object:Minesweeper::Tile
              flagged: false
              revealed: true
              row: 0
              col: 5
              neighbors:
              - *70116767944040
              - &70116767935560 !ruby/object:Minesweeper::Tile
                flagged: false
                revealed: true
                row: 0
                col: 6
                neighbors:
                - *70116767941640
                - &70116767933920 !ruby/object:Minesweeper::Tile
                  flagged: false
                  revealed: true
                  row: 0
                  col: 7
                  neighbors:
                  - *70116767935560
                  - &70116767931100 !ruby/object:Minesweeper::Tile
                    flagged: false
                    revealed: false
                    row: 0
                    col: 8
                    neighbors:
                    - *70116767933920
                    - &70116767929140 !ruby/object:Minesweeper::Tile
                      flagged: false
                      revealed: true
                      row: 1
                      col: 7
                      neighbors:
                      - *70116767935560
                      - *70116767933920
                      - *70116767931100
                      - &70116767928280 !ruby/object:Minesweeper::Tile
                        flagged: false
                        revealed: true
                        row: 1
                        col: 6
                        neighbors:
                        - *70116767941640
                        - *70116767935560
                        - *70116767933920
                        - &70116767906920 !ruby/object:Minesweeper::Tile
                          flagged: false
                          revealed: true
                          row: 1
                          col: 5
                          neighbors:
                          - *70116767944040
                          - *70116767941640
                          - *70116767935560
                          - &70116767906200 !ruby/object:Minesweeper::Tile
                            flagged: false
                            revealed: true
                            row: 1
                            col: 4
                            neighbors:
                            - *70116767945400
                            - *70116767944040
                            - *70116767941640
                            - &70116767905580 !ruby/object:Minesweeper::Tile
                              flagged: false
                              revealed: true
                              row: 1
                              col: 3
                              neighbors:
                              - *70116767947400
                              - *70116767945400
                              - *70116767944040
                              - &70116767904740 !ruby/object:Minesweeper::Tile
                                flagged: false
                                revealed: true
                                row: 1
                                col: 2
                                neighbors:
                                - *70116767950480
                                - *70116767947400
                                - *70116767945400
                                - &70116767904100 !ruby/object:Minesweeper::Tile
                                  flagged: false
                                  revealed: true
                                  row: 1
                                  col: 1
                                  neighbors:
                                  - *70116767962900
                                  - *70116767950480
                                  - *70116767947400
                                  - &70116767903420 !ruby/object:Minesweeper::Tile
                                    flagged: false
                                    revealed: true
                                    row: 1
                                    col: 0
                                    neighbors:
                                    - *70116767962900
                                    - *70116767950480
                                    - *70116767904100
                                    - &70116767902540 !ruby/object:Minesweeper::Tile
                                      flagged: false
                                      revealed: false
                                      row: 2
                                      col: 0
                                      neighbors:
                                      - *70116767903420
                                      - *70116767904100
                                      - &70116767901800 !ruby/object:Minesweeper::Tile
                                        flagged: false
                                        revealed: false
                                        row: 2
                                        col: 1
                                        neighbors:
                                        - *70116767903420
                                        - *70116767904100
                                        - *70116767904740
                                        - *70116767902540
                                        - &70116767900740 !ruby/object:Minesweeper::Tile
                                          flagged: false
                                          revealed: false
                                          row: 2
                                          col: 2
                                          neighbors:
                                          - *70116767904100
                                          - *70116767904740
                                          - *70116767905580
                                          - *70116767901800
                                          - &70116767898960 !ruby/object:Minesweeper::Tile
                                            flagged: false
                                            revealed: true
                                            row: 2
                                            col: 3
                                            neighbors:
                                            - *70116767904740
                                            - *70116767905580
                                            - *70116767906200
                                            - *70116767900740
                                            - &70116767898300 !ruby/object:Minesweeper::Tile
                                              flagged: false
                                              revealed: true
                                              row: 2
                                              col: 4
                                              neighbors:
                                              - *70116767905580
                                              - *70116767906200
                                              - *70116767906920
                                              - *70116767898960
                                              - &70116767897300 !ruby/object:Minesweeper::Tile
                                                flagged: false
                                                revealed: true
                                                row: 2
                                                col: 5
                                                neighbors:
                                                - *70116767906200
                                                - *70116767906920
                                                - *70116767928280
                                                - *70116767898300
                                                - &70116767896480 !ruby/object:Minesweeper::Tile
                                                  flagged: false
                                                  revealed: true
                                                  row: 2
                                                  col: 6
                                                  neighbors:
                                                  - *70116767906920
                                                  - *70116767928280
                                                  - *70116767929140
                                                  - *70116767897300
                                                  - &70116767895860 !ruby/object:Minesweeper::Tile
                                                    flagged: false
                                                    revealed: true
                                                    row: 2
                                                    col: 7
                                                    neighbors:
                                                    - *70116767928280
                                                    - *70116767929140
                                                    - &70116767895080 !ruby/object:Minesweeper::Tile
                                                      flagged: false
                                                      revealed: true
                                                      row: 1
                                                      col: 8
                                                      neighbors:
                                                      - *70116767933920
                                                      - *70116767931100
                                                      - *70116767929140
                                                      - *70116767895860
                                                      - &70116767894300 !ruby/object:Minesweeper::Tile
                                                        flagged: false
                                                        revealed: true
                                                        row: 2
                                                        col: 8
                                                        neighbors:
                                                        - *70116767929140
                                                        - *70116767895080
                                                        - *70116767895860
                                                        - &70116767893520 !ruby/object:Minesweeper::Tile
                                                          flagged: false
                                                          revealed: true
                                                          row: 3
                                                          col: 7
                                                          neighbors:
                                                          - *70116767896480
                                                          - *70116767895860
                                                          - *70116767894300
                                                          - &70116767892880 !ruby/object:Minesweeper::Tile
                                                            flagged: false
                                                            revealed: true
                                                            row: 3
                                                            col: 6
                                                            neighbors:
                                                            - *70116767897300
                                                            - *70116767896480
                                                            - *70116767895860
                                                            - &70116767892220 !ruby/object:Minesweeper::Tile
                                                              flagged: false
                                                              revealed: true
                                                              row: 3
                                                              col: 5
                                                              neighbors:
                                                              - *70116767898300
                                                              - *70116767897300
                                                              - *70116767896480
                                                              - &70116767891360 !ruby/object:Minesweeper::Tile
                                                                flagged: false
                                                                revealed: true
                                                                row: 3
                                                                col: 4
                                                                neighbors:
                                                                - *70116767898960
                                                                - *70116767898300
                                                                - *70116767897300
                                                                - &70116767858900 !ruby/object:Minesweeper::Tile
                                                                  flagged: false
                                                                  revealed: true
                                                                  row: 3
                                                                  col: 3
                                                                  neighbors:
                                                                  - *70116767900740
                                                                  - *70116767898960
                                                                  - *70116767898300
                                                                  - &70116767857000 !ruby/object:Minesweeper::Tile
                                                                    flagged: false
                                                                    revealed: false
                                                                    row: 3
                                                                    col: 2
                                                                    neighbors:
                                                                    - *70116767901800
                                                                    - *70116767900740
                                                                    - *70116767898960
                                                                    - &70116767855540 !ruby/object:Minesweeper::Tile
                                                                      flagged: false
                                                                      revealed: false
                                                                      row: 3
                                                                      col: 1
                                                                      neighbors:
                                                                      - *70116767902540
                                                                      - *70116767901800
                                                                      - *70116767900740
                                                                      - &70116767854940 !ruby/object:Minesweeper::Tile
                                                                        flagged: false
                                                                        revealed: false
                                                                        row: 3
                                                                        col: 0
                                                                        neighbors:
                                                                        - *70116767902540
                                                                        - *70116767901800
                                                                        - *70116767855540
                                                                        - &70116767854100 !ruby/object:Minesweeper::Tile
                                                                          flagged: false
                                                                          revealed: true
                                                                          row: 4
                                                                          col: 0
                                                                          neighbors:
                                                                          - *70116767854940
                                                                          - *70116767855540
                                                                          - &70116767842660 !ruby/object:Minesweeper::Tile
                                                                            flagged: false
                                                                            revealed: true
                                                                            row: 4
                                                                            col: 1
                                                                            neighbors:
                                                                            - *70116767854940
                                                                            - *70116767855540
                                                                            - *70116767857000
                                                                            - *70116767854100
                                                                            - &70116767839040 !ruby/object:Minesweeper::Tile
                                                                              flagged: false
                                                                              revealed: false
                                                                              row: 4
                                                                              col: 2
                                                                              neighbors:
                                                                              - *70116767855540
                                                                              - *70116767857000
                                                                              - *70116767858900
                                                                              - *70116767842660
                                                                              - &70116767829180 !ruby/object:Minesweeper::Tile
                                                                                flagged: false
                                                                                revealed: true
                                                                                row: 4
                                                                                col: 3
                                                                                neighbors:
                                                                                - *70116767857000
                                                                                - *70116767858900
                                                                                - *70116767891360
                                                                                - *70116767839040
                                                                                - &70116767827340 !ruby/object:Minesweeper::Tile
                                                                                  flagged: false
                                                                                  revealed: true
                                                                                  row: 4
                                                                                  col: 4
                                                                                  neighbors:
                                                                                  - *70116767858900
                                                                                  - *70116767891360
                                                                                  - *70116767892220
                                                                                  - *70116767829180
                                                                                  - &70116767824900 !ruby/object:Minesweeper::Tile
                                                                                    flagged: false
                                                                                    revealed: true
                                                                                    row: 4
                                                                                    col: 5
                                                                                    neighbors:
                                                                                    - *70116767891360
                                                                                    - *70116767892220
                                                                                    - *70116767892880
                                                                                    - *70116767827340
                                                                                    - &70116767810960 !ruby/object:Minesweeper::Tile
                                                                                      flagged: false
                                                                                      revealed: true
                                                                                      row: 4
                                                                                      col: 6
                                                                                      neighbors:
                                                                                      - *70116767892220
                                                                                      - *70116767892880
                                                                                      - *70116767893520
                                                                                      - *70116767824900
                                                                                      - &70116767806860 !ruby/object:Minesweeper::Tile
                                                                                        flagged: false
                                                                                        revealed: true
                                                                                        row: 4
                                                                                        col: 7
                                                                                        neighbors:
                                                                                        - *70116767892880
                                                                                        - *70116767893520
                                                                                        - &70116767802900 !ruby/object:Minesweeper::Tile
                                                                                          flagged: false
                                                                                          revealed: true
                                                                                          row: 3
                                                                                          col: 8
                                                                                          neighbors:
                                                                                          - *70116767895860
                                                                                          - *70116767894300
                                                                                          - *70116767893520
                                                                                          - *70116767806860
                                                                                          - &70116767793600 !ruby/object:Minesweeper::Tile
                                                                                            flagged: false
                                                                                            revealed: false
                                                                                            row: 4
                                                                                            col: 8
                                                                                            neighbors:
                                                                                            - *70116767893520
                                                                                            - *70116767802900
                                                                                            - *70116767806860
                                                                                            - &70116767780280 !ruby/object:Minesweeper::Tile
                                                                                              flagged: false
                                                                                              revealed: false
                                                                                              row: 5
                                                                                              col: 7
                                                                                              neighbors:
                                                                                              - *70116767810960
                                                                                              - *70116767806860
                                                                                              - *70116767793600
                                                                                              - &70116767774820 !ruby/object:Minesweeper::Tile
                                                                                                flagged: true
                                                                                                revealed: false
                                                                                                row: 5
                                                                                                col: 6
                                                                                                neighbors:
                                                                                                - *70116767824900
                                                                                                - *70116767810960
                                                                                                - *70116767806860
                                                                                                - &70116767774260 !ruby/object:Minesweeper::Tile
                                                                                                  flagged: false
                                                                                                  revealed: true
                                                                                                  row: 5
                                                                                                  col: 5
                                                                                                  neighbors:
                                                                                                  - *70116767827340
                                                                                                  - *70116767824900
                                                                                                  - *70116767810960
                                                                                                  - &70116767766600 !ruby/object:Minesweeper::Tile
                                                                                                    flagged: false
                                                                                                    revealed: true
                                                                                                    row: 5
                                                                                                    col: 4
                                                                                                    neighbors:
                                                                                                    - *70116767829180
                                                                                                    - *70116767827340
                                                                                                    - *70116767824900
                                                                                                    - &70116767763020 !ruby/object:Minesweeper::Tile
                                                                                                      flagged: false
                                                                                                      revealed: false
                                                                                                      row: 5
                                                                                                      col: 3
                                                                                                      neighbors:
                                                                                                      - *70116767839040
                                                                                                      - *70116767829180
                                                                                                      - *70116767827340
                                                                                                      - &70116767758700 !ruby/object:Minesweeper::Tile
                                                                                                        flagged: false
                                                                                                        revealed: false
                                                                                                        row: 5
                                                                                                        col: 2
                                                                                                        neighbors:
                                                                                                        - *70116767842660
                                                                                                        - *70116767839040
                                                                                                        - *70116767829180
                                                                                                        - &70116767757020 !ruby/object:Minesweeper::Tile
                                                                                                          flagged: false
                                                                                                          revealed: true
                                                                                                          row: 5
                                                                                                          col: 1
                                                                                                          neighbors:
                                                                                                          - *70116767854100
                                                                                                          - *70116767842660
                                                                                                          - *70116767839040
                                                                                                          - &70116767753680 !ruby/object:Minesweeper::Tile
                                                                                                            flagged: false
                                                                                                            revealed: true
                                                                                                            row: 5
                                                                                                            col: 0
                                                                                                            neighbors:
                                                                                                            - *70116767854100
                                                                                                            - *70116767842660
                                                                                                            - *70116767757020
                                                                                                            - &70116767742520 !ruby/object:Minesweeper::Tile
                                                                                                              flagged: false
                                                                                                              revealed: true
                                                                                                              row: 6
                                                                                                              col: 0
                                                                                                              neighbors:
                                                                                                              - *70116767753680
                                                                                                              - *70116767757020
                                                                                                              - &70116767739940 !ruby/object:Minesweeper::Tile
                                                                                                                flagged: false
                                                                                                                revealed: true
                                                                                                                row: 6
                                                                                                                col: 1
                                                                                                                neighbors:
                                                                                                                - *70116767753680
                                                                                                                - *70116767757020
                                                                                                                - *70116767758700
                                                                                                                - *70116767742520
                                                                                                                - &70116767558620 !ruby/object:Minesweeper::Tile
                                                                                                                  flagged: false
                                                                                                                  revealed: false
                                                                                                                  row: 6
                                                                                                                  col: 2
                                                                                                                  neighbors:
                                                                                                                  - *70116767757020
                                                                                                                  - *70116767758700
                                                                                                                  - *70116767763020
                                                                                                                  - *70116767739940
                                                                                                                  - &70116767553860 !ruby/object:Minesweeper::Tile
                                                                                                                    flagged: false
                                                                                                                    revealed: false
                                                                                                                    row: 6
                                                                                                                    col: 3
                                                                                                                    neighbors:
                                                                                                                    - *70116767758700
                                                                                                                    - *70116767763020
                                                                                                                    - *70116767766600
                                                                                                                    - *70116767558620
                                                                                                                    - &70116767714060 !ruby/object:Minesweeper::Tile
                                                                                                                      flagged: false
                                                                                                                      revealed: true
                                                                                                                      row: 6
                                                                                                                      col: 4
                                                                                                                      neighbors:
                                                                                                                      - *70116767763020
                                                                                                                      - *70116767766600
                                                                                                                      - *70116767774260
                                                                                                                      - *70116767553860
                                                                                                                      - &70116767711220 !ruby/object:Minesweeper::Tile
                                                                                                                        flagged: false
                                                                                                                        revealed: true
                                                                                                                        row: 6
                                                                                                                        col: 5
                                                                                                                        neighbors:
                                                                                                                        - *70116767766600
                                                                                                                        - *70116767774260
                                                                                                                        - *70116767774820
                                                                                                                        - *70116767714060
                                                                                                                        - &70116767691280 !ruby/object:Minesweeper::Tile
                                                                                                                          flagged: false
                                                                                                                          revealed: true
                                                                                                                          row: 6
                                                                                                                          col: 6
                                                                                                                          neighbors:
                                                                                                                          - *70116767774260
                                                                                                                          - *70116767774820
                                                                                                                          - *70116767780280
                                                                                                                          - *70116767711220
                                                                                                                          - &70116767684040 !ruby/object:Minesweeper::Tile
                                                                                                                            flagged: false
                                                                                                                            revealed: false
                                                                                                                            row: 6
                                                                                                                            col: 7
                                                                                                                            neighbors:
                                                                                                                            - *70116767774820
                                                                                                                            - *70116767780280
                                                                                                                            - &70116767679760 !ruby/object:Minesweeper::Tile
                                                                                                                              flagged: false
                                                                                                                              revealed: false
                                                                                                                              row: 5
                                                                                                                              col: 8
                                                                                                                              neighbors:
                                                                                                                              - *70116767806860
                                                                                                                              - *70116767793600
                                                                                                                              - *70116767780280
                                                                                                                              - *70116767684040
                                                                                                                              - &70116767674360 !ruby/object:Minesweeper::Tile
                                                                                                                                flagged: false
                                                                                                                                revealed: false
                                                                                                                                row: 6
                                                                                                                                col: 8
                                                                                                                                neighbors:
                                                                                                                                - *70116767780280
                                                                                                                                - *70116767679760
                                                                                                                                - *70116767684040
                                                                                                                                - &70116767672200 !ruby/object:Minesweeper::Tile
                                                                                                                                  flagged: false
                                                                                                                                  revealed: false
                                                                                                                                  row: 7
                                                                                                                                  col: 7
                                                                                                                                  neighbors:
                                                                                                                                  - *70116767691280
                                                                                                                                  - *70116767684040
                                                                                                                                  - *70116767674360
                                                                                                                                  - &70116767620580 !ruby/object:Minesweeper::Tile
                                                                                                                                    flagged: false
                                                                                                                                    revealed: false
                                                                                                                                    row: 7
                                                                                                                                    col: 6
                                                                                                                                    neighbors:
                                                                                                                                    - *70116767711220
                                                                                                                                    - *70116767691280
                                                                                                                                    - *70116767684040
                                                                                                                                    - &70116767616060 !ruby/object:Minesweeper::Tile
                                                                                                                                      flagged: false
                                                                                                                                      revealed: false
                                                                                                                                      row: 7
                                                                                                                                      col: 5
                                                                                                                                      neighbors:
                                                                                                                                      - *70116767714060
                                                                                                                                      - *70116767711220
                                                                                                                                      - *70116767691280
                                                                                                                                      - &70116767612700 !ruby/object:Minesweeper::Tile
                                                                                                                                        flagged: false
                                                                                                                                        revealed: false
                                                                                                                                        row: 7
                                                                                                                                        col: 4
                                                                                                                                        neighbors:
                                                                                                                                        - *70116767553860
                                                                                                                                        - *70116767714060
                                                                                                                                        - *70116767711220
                                                                                                                                        - &70116767610180 !ruby/object:Minesweeper::Tile
                                                                                                                                          flagged: false
                                                                                                                                          revealed: true
                                                                                                                                          row: 7
                                                                                                                                          col: 3
                                                                                                                                          neighbors:
                                                                                                                                          - *70116767558620
                                                                                                                                          - *70116767553860
                                                                                                                                          - *70116767714060
                                                                                                                                          - &70116767606940 !ruby/object:Minesweeper::Tile
                                                                                                                                            flagged: false
                                                                                                                                            revealed: true
                                                                                                                                            row: 7
                                                                                                                                            col: 2
                                                                                                                                            neighbors:
                                                                                                                                            - *70116767739940
                                                                                                                                            - *70116767558620
                                                                                                                                            - *70116767553860
                                                                                                                                            - &70116767603880 !ruby/object:Minesweeper::Tile
                                                                                                                                              flagged: false
                                                                                                                                              revealed: true
                                                                                                                                              row: 7
                                                                                                                                              col: 1
                                                                                                                                              neighbors:
                                                                                                                                              - *70116767742520
                                                                                                                                              - *70116767739940
                                                                                                                                              - *70116767558620
                                                                                                                                              - &70116767599100 !ruby/object:Minesweeper::Tile
                                                                                                                                                flagged: false
                                                                                                                                                revealed: true
                                                                                                                                                row: 7
                                                                                                                                                col: 0
                                                                                                                                                neighbors:
                                                                                                                                                - *70116767742520
                                                                                                                                                - *70116767739940
                                                                                                                                                - *70116767603880
                                                                                                                                                - &70116767546400 !ruby/object:Minesweeper::Tile
                                                                                                                                                  flagged: false
                                                                                                                                                  revealed: true
                                                                                                                                                  row: 8
                                                                                                                                                  col: 0
                                                                                                                                                  neighbors:
                                                                                                                                                  - *70116767599100
                                                                                                                                                  - *70116767603880
                                                                                                                                                  - &70116767538240 !ruby/object:Minesweeper::Tile
                                                                                                                                                    flagged: false
                                                                                                                                                    revealed: true
                                                                                                                                                    row: 8
                                                                                                                                                    col: 1
                                                                                                                                                    neighbors:
                                                                                                                                                    - *70116767599100
                                                                                                                                                    - *70116767603880
                                                                                                                                                    - *70116767606940
                                                                                                                                                    - *70116767546400
                                                                                                                                                    - &70116767393220 !ruby/object:Minesweeper::Tile
                                                                                                                                                      flagged: false
                                                                                                                                                      revealed: true
                                                                                                                                                      row: 8
                                                                                                                                                      col: 2
                                                                                                                                                      neighbors:
                                                                                                                                                      - *70116767603880
                                                                                                                                                      - *70116767606940
                                                                                                                                                      - *70116767610180
                                                                                                                                                      - *70116767538240
                                                                                                                                                      - &70116767390280 !ruby/object:Minesweeper::Tile
                                                                                                                                                        flagged: false
                                                                                                                                                        revealed: true
                                                                                                                                                        row: 8
                                                                                                                                                        col: 3
                                                                                                                                                        neighbors:
                                                                                                                                                        - *70116767606940
                                                                                                                                                        - *70116767610180
                                                                                                                                                        - *70116767612700
                                                                                                                                                        - *70116767393220
                                                                                                                                                        - &70116767536180 !ruby/object:Minesweeper::Tile
                                                                                                                                                          flagged: false
                                                                                                                                                          revealed: false
                                                                                                                                                          row: 8
                                                                                                                                                          col: 4
                                                                                                                                                          neighbors:
                                                                                                                                                          - *70116767610180
                                                                                                                                                          - *70116767612700
                                                                                                                                                          - *70116767616060
                                                                                                                                                          - *70116767390280
                                                                                                                                                          - &70116767533540 !ruby/object:Minesweeper::Tile
                                                                                                                                                            flagged: false
                                                                                                                                                            revealed: false
                                                                                                                                                            row: 8
                                                                                                                                                            col: 5
                                                                                                                                                            neighbors:
                                                                                                                                                            - *70116767612700
                                                                                                                                                            - *70116767616060
                                                                                                                                                            - *70116767620580
                                                                                                                                                            - *70116767536180
                                                                                                                                                            - &70116767531620 !ruby/object:Minesweeper::Tile
                                                                                                                                                              flagged: false
                                                                                                                                                              revealed: false
                                                                                                                                                              row: 8
                                                                                                                                                              col: 6
                                                                                                                                                              neighbors:
                                                                                                                                                              - *70116767616060
                                                                                                                                                              - *70116767620580
                                                                                                                                                              - *70116767672200
                                                                                                                                                              - *70116767533540
                                                                                                                                                              - &70116767527740 !ruby/object:Minesweeper::Tile
                                                                                                                                                                flagged: false
                                                                                                                                                                revealed: false
                                                                                                                                                                row: 8
                                                                                                                                                                col: 7
                                                                                                                                                                neighbors:
                                                                                                                                                                - *70116767620580
                                                                                                                                                                - *70116767672200
                                                                                                                                                                - &70116767526680 !ruby/object:Minesweeper::Tile
                                                                                                                                                                  flagged: false
                                                                                                                                                                  revealed: false
                                                                                                                                                                  row: 7
                                                                                                                                                                  col: 8
                                                                                                                                                                  neighbors:
                                                                                                                                                                  - *70116767684040
                                                                                                                                                                  - *70116767674360
                                                                                                                                                                  - *70116767672200
                                                                                                                                                                  - *70116767527740
                                                                                                                                                                  - &70116767525200 !ruby/object:Minesweeper::Tile
                                                                                                                                                                    flagged: false
                                                                                                                                                                    revealed: false
                                                                                                                                                                    row: 8
                                                                                                                                                                    col: 8
                                                                                                                                                                    neighbors:
                                                                                                                                                                    - *70116767672200
                                                                                                                                                                    - *70116767526680
                                                                                                                                                                    - *70116767527740
                                                                                                                                                                - *70116767531620
                                                                                                                                                                - *70116767525200
                                                                                                                                                        neighbor_bomb_count: 1
                                                                                                                                                      neighbor_bomb_count: 0
                                                                                                                                                    neighbor_bomb_count: 0
                                                                                                                                                  neighbor_bomb_count: 0
                                                                                                                                                - *70116767538240
                                                                                                                                                neighbor_bomb_count: 0
                                                                                                                                              - *70116767606940
                                                                                                                                              - *70116767546400
                                                                                                                                              - *70116767538240
                                                                                                                                              - *70116767393220
                                                                                                                                              neighbor_bomb_count: 1
                                                                                                                                            - *70116767610180
                                                                                                                                            - *70116767538240
                                                                                                                                            - *70116767393220
                                                                                                                                            - *70116767390280
                                                                                                                                            neighbor_bomb_count: 1
                                                                                                                                          - *70116767612700
                                                                                                                                          - *70116767393220
                                                                                                                                          - *70116767390280
                                                                                                                                          - *70116767536180
                                                                                                                                          neighbor_bomb_count: 2
                                                                                                                                        - *70116767616060
                                                                                                                                        - *70116767390280
                                                                                                                                        - *70116767536180
                                                                                                                                        - *70116767533540
                                                                                                                                        bombed: true
                                                                                                                                      - *70116767620580
                                                                                                                                      - *70116767536180
                                                                                                                                      - *70116767533540
                                                                                                                                      - *70116767531620
                                                                                                                                    - *70116767672200
                                                                                                                                    - *70116767533540
                                                                                                                                    - *70116767531620
                                                                                                                                    - *70116767527740
                                                                                                                                  - *70116767526680
                                                                                                                                  - *70116767531620
                                                                                                                                  - *70116767527740
                                                                                                                                  - *70116767525200
                                                                                                                                - *70116767526680
                                                                                                                            - *70116767691280
                                                                                                                            - *70116767674360
                                                                                                                            - *70116767620580
                                                                                                                            - *70116767672200
                                                                                                                            - *70116767526680
                                                                                                                          - *70116767616060
                                                                                                                          - *70116767620580
                                                                                                                          - *70116767672200
                                                                                                                          neighbor_bomb_count: 1
                                                                                                                        - *70116767612700
                                                                                                                        - *70116767616060
                                                                                                                        - *70116767620580
                                                                                                                        neighbor_bomb_count: 1
                                                                                                                      - *70116767610180
                                                                                                                      - *70116767612700
                                                                                                                      - *70116767616060
                                                                                                                      neighbor_bomb_count: 2
                                                                                                                    - *70116767606940
                                                                                                                    - *70116767610180
                                                                                                                    - *70116767612700
                                                                                                                  - *70116767603880
                                                                                                                  - *70116767606940
                                                                                                                  - *70116767610180
                                                                                                                  bombed: true
                                                                                                                - *70116767599100
                                                                                                                - *70116767603880
                                                                                                                - *70116767606940
                                                                                                                neighbor_bomb_count: 1
                                                                                                              - *70116767599100
                                                                                                              - *70116767603880
                                                                                                              neighbor_bomb_count: 0
                                                                                                            - *70116767739940
                                                                                                            neighbor_bomb_count: 0
                                                                                                          - *70116767758700
                                                                                                          - *70116767742520
                                                                                                          - *70116767739940
                                                                                                          - *70116767558620
                                                                                                          neighbor_bomb_count: 1
                                                                                                        - *70116767763020
                                                                                                        - *70116767739940
                                                                                                        - *70116767558620
                                                                                                        - *70116767553860
                                                                                                      - *70116767766600
                                                                                                      - *70116767558620
                                                                                                      - *70116767553860
                                                                                                      - *70116767714060
                                                                                                      bombed: true
                                                                                                    - *70116767774260
                                                                                                    - *70116767553860
                                                                                                    - *70116767714060
                                                                                                    - *70116767711220
                                                                                                    neighbor_bomb_count: 1
                                                                                                  - *70116767774820
                                                                                                  - *70116767714060
                                                                                                  - *70116767711220
                                                                                                  - *70116767691280
                                                                                                  neighbor_bomb_count: 0
                                                                                                - *70116767780280
                                                                                                - *70116767711220
                                                                                                - *70116767691280
                                                                                                - *70116767684040
                                                                                              - *70116767679760
                                                                                              - *70116767691280
                                                                                              - *70116767684040
                                                                                              - *70116767674360
                                                                                              bombed: true
                                                                                            - *70116767679760
                                                                                            bombed: true
                                                                                          neighbor_bomb_count: 1
                                                                                        - *70116767810960
                                                                                        - *70116767793600
                                                                                        - *70116767774820
                                                                                        - *70116767780280
                                                                                        - *70116767679760
                                                                                        neighbor_bomb_count: 2
                                                                                      - *70116767774260
                                                                                      - *70116767774820
                                                                                      - *70116767780280
                                                                                      neighbor_bomb_count: 1
                                                                                    - *70116767766600
                                                                                    - *70116767774260
                                                                                    - *70116767774820
                                                                                    neighbor_bomb_count: 0
                                                                                  - *70116767763020
                                                                                  - *70116767766600
                                                                                  - *70116767774260
                                                                                  neighbor_bomb_count: 1
                                                                                - *70116767758700
                                                                                - *70116767763020
                                                                                - *70116767766600
                                                                                neighbor_bomb_count: 1
                                                                              - *70116767757020
                                                                              - *70116767758700
                                                                              - *70116767763020
                                                                            - *70116767753680
                                                                            - *70116767757020
                                                                            - *70116767758700
                                                                            neighbor_bomb_count: 2
                                                                          - *70116767753680
                                                                          - *70116767757020
                                                                          neighbor_bomb_count: 2
                                                                        - *70116767842660
                                                                        bombed: true
                                                                      - *70116767857000
                                                                      - *70116767854100
                                                                      - *70116767842660
                                                                      - *70116767839040
                                                                      bombed: true
                                                                    - *70116767858900
                                                                    - *70116767842660
                                                                    - *70116767839040
                                                                    - *70116767829180
                                                                  - *70116767891360
                                                                  - *70116767839040
                                                                  - *70116767829180
                                                                  - *70116767827340
                                                                  neighbor_bomb_count: 1
                                                                - *70116767892220
                                                                - *70116767829180
                                                                - *70116767827340
                                                                - *70116767824900
                                                                neighbor_bomb_count: 0
                                                              - *70116767892880
                                                              - *70116767827340
                                                              - *70116767824900
                                                              - *70116767810960
                                                              neighbor_bomb_count: 0
                                                            - *70116767893520
                                                            - *70116767824900
                                                            - *70116767810960
                                                            - *70116767806860
                                                            neighbor_bomb_count: 0
                                                          - *70116767802900
                                                          - *70116767810960
                                                          - *70116767806860
                                                          - *70116767793600
                                                          neighbor_bomb_count: 1
                                                        - *70116767802900
                                                        neighbor_bomb_count: 0
                                                      neighbor_bomb_count: 1
                                                    - *70116767896480
                                                    - *70116767894300
                                                    - *70116767892880
                                                    - *70116767893520
                                                    - *70116767802900
                                                    neighbor_bomb_count: 0
                                                  - *70116767892220
                                                  - *70116767892880
                                                  - *70116767893520
                                                  neighbor_bomb_count: 0
                                                - *70116767891360
                                                - *70116767892220
                                                - *70116767892880
                                                neighbor_bomb_count: 0
                                              - *70116767858900
                                              - *70116767891360
                                              - *70116767892220
                                              neighbor_bomb_count: 0
                                            - *70116767857000
                                            - *70116767858900
                                            - *70116767891360
                                            neighbor_bomb_count: 1
                                          - *70116767855540
                                          - *70116767857000
                                          - *70116767858900
                                          bombed: true
                                        - *70116767854940
                                        - *70116767855540
                                        - *70116767857000
                                      - *70116767854940
                                      - *70116767855540
                                      bombed: true
                                    - *70116767901800
                                    neighbor_bomb_count: 1
                                  - *70116767904740
                                  - *70116767902540
                                  - *70116767901800
                                  - *70116767900740
                                  neighbor_bomb_count: 2
                                - *70116767905580
                                - *70116767901800
                                - *70116767900740
                                - *70116767898960
                                neighbor_bomb_count: 1
                              - *70116767906200
                              - *70116767900740
                              - *70116767898960
                              - *70116767898300
                              neighbor_bomb_count: 1
                            - *70116767906920
                            - *70116767898960
                            - *70116767898300
                            - *70116767897300
                            neighbor_bomb_count: 0
                          - *70116767928280
                          - *70116767898300
                          - *70116767897300
                          - *70116767896480
                          neighbor_bomb_count: 0
                        - *70116767929140
                        - *70116767897300
                        - *70116767896480
                        - *70116767895860
                        neighbor_bomb_count: 0
                      - *70116767895080
                      - *70116767896480
                      - *70116767895860
                      - *70116767894300
                      neighbor_bomb_count: 1
                    - *70116767895080
                    bombed: true
                  - *70116767928280
                  - *70116767929140
                  - *70116767895080
                  neighbor_bomb_count: 1
                - *70116767906920
                - *70116767928280
                - *70116767929140
                neighbor_bomb_count: 0
              - *70116767906200
              - *70116767906920
              - *70116767928280
              neighbor_bomb_count: 0
            - *70116767905580
            - *70116767906200
            - *70116767906920
            neighbor_bomb_count: 0
          - *70116767904740
          - *70116767905580
          - *70116767906200
          neighbor_bomb_count: 0
        - *70116767904100
        - *70116767904740
        - *70116767905580
        neighbor_bomb_count: 0
      - *70116767903420
      - *70116767904100
      - *70116767904740
      neighbor_bomb_count: 0
    - *70116767903420
    - *70116767904100
    neighbor_bomb_count: 0
  - *70116767950480
  - *70116767947400
  - *70116767945400
  - *70116767944040
  - *70116767941640
  - *70116767935560
  - *70116767933920
  - *70116767931100
- - *70116767903420
  - *70116767904100
  - *70116767904740
  - *70116767905580
  - *70116767906200
  - *70116767906920
  - *70116767928280
  - *70116767929140
  - *70116767895080
- - *70116767902540
  - *70116767901800
  - *70116767900740
  - *70116767898960
  - *70116767898300
  - *70116767897300
  - *70116767896480
  - *70116767895860
  - *70116767894300
- - *70116767854940
  - *70116767855540
  - *70116767857000
  - *70116767858900
  - *70116767891360
  - *70116767892220
  - *70116767892880
  - *70116767893520
  - *70116767802900
- - *70116767854100
  - *70116767842660
  - *70116767839040
  - *70116767829180
  - *70116767827340
  - *70116767824900
  - *70116767810960
  - *70116767806860
  - *70116767793600
- - *70116767753680
  - *70116767757020
  - *70116767758700
  - *70116767763020
  - *70116767766600
  - *70116767774260
  - *70116767774820
  - *70116767780280
  - *70116767679760
- - *70116767742520
  - *70116767739940
  - *70116767558620
  - *70116767553860
  - *70116767714060
  - *70116767711220
  - *70116767691280
  - *70116767684040
  - *70116767674360
- - *70116767599100
  - *70116767603880
  - *70116767606940
  - *70116767610180
  - *70116767612700
  - *70116767616060
  - *70116767620580
  - *70116767672200
  - *70116767526680
- - *70116767546400
  - *70116767538240
  - *70116767393220
  - *70116767390280
  - *70116767536180
  - *70116767533540
  - *70116767531620
  - *70116767527740
  - *70116767525200
